name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t llm-devops-app:ci .

      - name: Run container
        run: docker run -d --name llm-api-test -p 8001:8001 llm-devops-app:ci

      - name: Test API
        run: |
          sleep 5
          curl -f http://localhost:8001/

      - name: Stop test container
        if: always()
        run: docker rm -f llm-api-test